apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ogyz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ogyz
    app.kubernetes.io/part-of: tkrw-pr712-0075-0057-app
  name: devfile-sample-ogyz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ogyz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ogyz
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0057-tenant/tkrw-pr712-0075-0057-app/devfile-sample-ogyz@sha256:e6ce3f6f515f33c0e0692a02fa8e62b39c651703e5cb726328dda3aa95b6e756
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
